# Generated by Django 4.1.5 on 2023-03-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login_V1", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ipblock",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ipblock",
            name="ip_range",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
