# Generated by Django 4.1.5 on 2023-01-08 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="activity_report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reporter_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reporter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "reporter_phone",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reporter_address",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("image", models.ImageField(blank=True, upload_to="images")),
                ("video", models.FileField(blank=True, upload_to="videos")),
                ("audio", models.FileField(blank=True, upload_to="audios")),
                ("save_date_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
