# Generated by Django 4.1.5 on 2023-01-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity_report",
            name="audio",
        ),
    ]
