# Generated by Django 4.1.5 on 2023-01-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_person_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity_report",
            name="false_alarm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity_report",
            name="invistigated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person_report",
            name="false_alarm",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="person_report",
            name="invistigated",
            field=models.BooleanField(default=False),
        ),
    ]
