# Generated by Django 4.1.5 on 2023-03-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_wanted_list"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person_report",
            name="description",
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="wanted_list",
            name="caught_crime",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="wanted_list",
            name="caught_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wanted_list",
            name="caught_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="wanted_list",
            name="cloth_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="wanted_list",
            name="hair_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="wanted_list",
            name="height_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="wanted_list",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
